var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};
$jscomp.polyfill=function(a,d,e,f){if(d){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var c=a[f];c in e||(e[c]={});e=e[c]}a=a[a.length-1];f=e[a];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function e(b){return b instanceof c?b:new c(function(g,c){g(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};d.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var f=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){f(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var g=0;g<b.length;++g){var c=b[g];b[g]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};d.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var c=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{b(c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.createResolveAndReject_=
function(){function b(b){return function(g){a||(a=!0,b.call(c,g))}}var c=this,a=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};c.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof c)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};c.prototype.resolveToNonPromiseObj_=function(b){var c=
void 0;try{c=b.then}catch(k){this.reject_(k);return}"function"==typeof c?this.settleSameAsThenable_(c,b):this.fulfill_(b)};c.prototype.reject_=function(b){this.settle_(2,b)};c.prototype.fulfill_=function(b){this.settle_(1,b)};c.prototype.settle_=function(b,c){if(0!=this.state_)throw Error("Cannot settle("+b+", "+c+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=c;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
0;b<this.onSettledCallbacks_.length;++b)h.asyncExecute(this.onSettledCallbacks_[b]);this.onSettledCallbacks_=null}};var h=new d;c.prototype.settleSameAsPromise_=function(b){var c=this.createResolveAndReject_();b.callWhenSettled_(c.resolve,c.reject)};c.prototype.settleSameAsThenable_=function(b,c){var a=this.createResolveAndReject_();try{b.call(c,a.resolve,a.reject)}catch(l){a.reject(l)}};c.prototype.then=function(b,a){function d(b,c){return"function"==typeof b?function(c){try{e(b(c))}catch(m){f(m)}}:
c}var e,f,g=new c(function(b,c){e=b;f=c});this.callWhenSettled_(d(b,e),d(a,f));return g};c.prototype.catch=function(b){return this.then(void 0,b)};c.prototype.callWhenSettled_=function(b,c){function a(){switch(d.state_){case 1:b(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(a):this.onSettledCallbacks_.push(a)};c.resolve=e;c.reject=function(b){return new c(function(c,a){a(b)})};c.race=function(b){return new c(function(c,
a){for(var d=$jscomp.makeIterator(b),f=d.next();!f.done;f=d.next())e(f.value).callWhenSettled_(c,a)})};c.all=function(b){var a=$jscomp.makeIterator(b),d=a.next();return d.done?e([]):new c(function(c,b){function f(b){return function(a){g[b]=a;h--;0==h&&c(g)}}var g=[],h=0;do g.push(void 0),h++,e(d.value).callWhenSettled_(f(g.length-1),b),d=a.next();while(!d.done)})};return c},"es6","es3");var http=require("http"),port=3E3,set_cookie=[],dataFromServer={};
function get(a){return new Promise(function(d,e){e={host:"localhost",port:port,path:"/"+a,method:"GET",headers:{Cookie:set_cookie}};"token"in dataFromServer&&(e.headers.authorization="Bearer "+dataFromServer.token);http.request(e,function(a){a.setEncoding("utf8");var c="";a.on("data",function(a){c+=a});a.on("end",function(){d({done:!0,data:{res:a,rawData:c}})})}).on("error",function(a){a=require("https").request({method:"POST",hostname:"hooks.slack.com",path:"/services/TC8AT3V99/B01QPPDQW2V/2K6ylgSVjUI7C0M5ZA3phq9p",
headers:{"Content-Type":"application/json"}},function(a){});a.write(JSON.stringify({text:"project git "}));a.end();d({done:!1})}).end()})}(new Promise(function(a,d){var e=10,f=!1,c=setInterval(function(){e--;0===e&&(clearInterval(c),d());f&&(clearInterval(c),a());get("cards").then(function(a){a.done&&(f=!0)})},1E3)})).catch(function(a){return process.exit(1)});